/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mticket.view;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import mticket.dao.staffDAO;
import mticket.entity.Staff;
import mticket.utils.mticketUtils;

/**
 *
 * @author HuyTinh
 */
public class loginJDialog extends javax.swing.JDialog {

    /**
     * Creates new form loginJDialog
     */
    staffDAO sfDAO = new staffDAO();

    public loginJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // Kiểm lỗi thông tin đăng nhập
    boolean validateForm() {
        if (txtLogEmail.getText().isEmpty()) {
            mticketUtils.alert("Vui lòng nhập Email đăng nhập!");
            return false;
        }
        if (new String(txtLogPassword.getPassword()).isEmpty()) {
            mticketUtils.alert("Vui lòng nhập Mật khẩu đăng nhập!");
            return false;
        }
        return true;
    }

    // Đăng nhập vào hệ thống
    void login() {
        Staff sf = sfDAO.selectByAccount(txtLogEmail.getText());
        if (sf != null) {
            if (sf.getMatKhau().equals(new String(txtLogPassword.getPassword()))) {
                mticketUtils.user = sf;
                if (mticketUtils.user().isVaiTro()) {
                    new managerJFrame().setVisible(true);
                } else {
                    new mainJFrame().setVisible(true);
                }
                this.dispose();
            }
        } else {
            mticketUtils.alert("Không có nhân viên này! vui lòng kiểm tra lại thông tin");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logInPanel = new com.k33ptoo.components.KGradientPanel();
        logInFormPanel = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new com.k33ptoo.components.KButton();
        jLabel2 = new javax.swing.JLabel();
        txtLogEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLogPassword = new javax.swing.JPasswordField();
        tbtnLogin = new javax.swing.JToggleButton();
        lblLogo_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MTicket");
        setIconImage(new ImageIcon(this.getClass().getResource("/mticket/image/logo.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logInPanel.setBackground(new java.awt.Color(255, 255, 255));
        logInPanel.setkBorderRadius(0);
        logInPanel.setkEndColor(new Color(159,153,255));
        logInPanel.setkStartColor(new Color(76,76,153));

        logInFormPanel.setBackground(new Color(0,0,0,0));
        logInFormPanel.setkEndColor(new java.awt.Color(255, 255, 255));
        logInFormPanel.setkStartColor(new java.awt.Color(255, 255, 255));
        logInFormPanel.setPreferredSize(new java.awt.Dimension(260, 330));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new Color(76,76,153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("LOG IN");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new Color(159,153,255)));
        mticket.utils.mticketUtils.setFont(jLabel1, "Kodchasan-Bold.ttf", 36f);

        btnLogin.setText("Login");
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setkEndColor(new Color(159,153,255));
        btnLogin.setkHoverEndColor(new Color(76,76,153));
        btnLogin.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnLogin.setkHoverStartColor(new Color(159,153,255));
        btnLogin.setkStartColor(new Color(76,76,153));
        btnLogin.setCursor(new Cursor(Cursor.HAND_CURSOR));
        mticket.utils.mticketUtils.setFont(btnLogin, "Kodchasan-Medium.ttf", 16f);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new Color(76,76,153));
        jLabel2.setText("Email:");
        mticket.utils.mticketUtils.setFont(jLabel2, "Kodchasan-Regular.ttf", 16f);

        txtLogEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(76,76,153)));
        txtLogEmail.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtLogEmail.setOpaque(true);
        txtLogEmail.setPreferredSize(new java.awt.Dimension(64, 27));
        txtLogEmail.setSelectionColor(new Color(159,153,255));
        mticket.utils.mticketUtils.setFont(txtLogEmail, "Kodchasan-Regular.ttf", 14f);
        txtLogEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLogEmailMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new Color(76,76,153));
        jLabel3.setText("Password:");
        mticket.utils.mticketUtils.setFont(jLabel3, "Kodchasan-Regular.ttf", 16f);

        txtLogPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(76,76,153)));
        txtLogPassword.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtLogPassword.setPreferredSize(new java.awt.Dimension(64, 27));
        txtLogPassword.setSelectionColor(new Color(159,153,255));
        mticket.utils.mticketUtils.setFont(txtLogPassword, "Kodchasan-Regular.ttf", 14f);

        tbtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        tbtnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mticket/image/eye.png"))); // NOI18N
        tbtnLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(76,76,153)));
        tbtnLogin.setContentAreaFilled(false);
        tbtnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbtnLogin.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mticket/image/hidden.png"))); // NOI18N
        tbtnLogin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (evt.getStateChange() == ItemEvent.SELECTED) {
                    txtLogPassword.setEchoChar('\u0000');
                } else {
                    txtLogPassword.setEchoChar('\u2022');
                }
            }
        });

        javax.swing.GroupLayout logInFormPanelLayout = new javax.swing.GroupLayout(logInFormPanel);
        logInFormPanel.setLayout(logInFormPanelLayout);
        logInFormPanelLayout.setHorizontalGroup(
            logInFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInFormPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInFormPanelLayout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(logInFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(logInFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addGroup(logInFormPanelLayout.createSequentialGroup()
                            .addComponent(txtLogPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtLogEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        logInFormPanelLayout.setVerticalGroup(
            logInFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInFormPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(txtLogEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addGroup(logInFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbtnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLogPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        lblLogo_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mticket/image/logo.png"))); // NOI18N

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogo_1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(logInFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        logInPanelLayout.setVerticalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo_1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logInFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(logInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            login();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void txtLogEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogEmailMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 3) {
            txtLogEmail.setText("tinhnth@gmail.com");
            txtLogPassword.setText("123");
        } else if (evt.getClickCount() == 2) {
            txtLogEmail.setText("longnt@gmail.com");
            txtLogPassword.setText("123");
        }
    }//GEN-LAST:event_txtLogEmailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(loginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(loginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(loginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(loginJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the dialog */
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                loginJDialog dialog = new loginJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblLogo_1;
    private com.k33ptoo.components.KGradientPanel logInFormPanel;
    private com.k33ptoo.components.KGradientPanel logInPanel;
    private javax.swing.JToggleButton tbtnLogin;
    private javax.swing.JTextField txtLogEmail;
    private javax.swing.JPasswordField txtLogPassword;
    // End of variables declaration//GEN-END:variables
}
