/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mticket.component.schedule;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.TransferHandler;
import static mticket.component.schedule.movieSchedulePanel.mSP;
import mticket.dao.movieDAO;
import mticket.dao.movieScheduleDAO;
import mticket.dao.roomDAO;
import mticket.dao.showTimeDAO;
import mticket.entity.Movie;
import mticket.entity.MovieSchedule;
import mticket.utils.mticketUtils;

/**
 *
 * @author HuyTinh
 */
public class editMovieScheduleCard extends javax.swing.JPanel {

    /**
     * Creates new form editMovieCard
     */
    private MovieSchedule mS;
    movieScheduleDAO mSDAO = new movieScheduleDAO();

    public editMovieScheduleCard(String suatChieu, Movie... mvs) {
        initComponents();
        if (mvs.length > 0) {
            if (mvs[0] != null) {
                mticket.utils.mticketUtils.setIcon(new ImageIcon(getClass().getResource("/mticket/image/" + mvs[0].getHinhAnh())), lblAnh);
                mS = new movieScheduleDAO().getMovieSchedule(mvs[0].getMaPhim(), String.valueOf(mSP.getCboPhong().getSelectedItem()), String.valueOf(mSP.getCboNgay().getSelectedItem()));
                setName(mvs[0].getMaPhim());
                lblDrop.setVisible(false);
            }
        }
        lblAnh.setTransferHandler(new TransferHandler() {
            @Override
            public boolean canImport(TransferHandler.TransferSupport support) {
                return true;
            }

            @Override
            public boolean importData(JComponent comp, Transferable t) {

                try {
                    String idPhim = String.valueOf(t.getTransferData(t.getTransferDataFlavors()[0]));
                    Movie mv = new movieDAO().selectById(idPhim);
                    mticket.utils.mticketUtils.setIcon(new ImageIcon(getClass().getResource("/mticket/image/" + mv.getHinhAnh())), lblAnh);
                    setName(idPhim);
                    MovieSchedule ms = new MovieSchedule(mSDAO.getIncreadMovieScheduleID(), getName(), new roomDAO().getMaPhong(String.valueOf(mSP.getCboPhong().getSelectedItem())), new showTimeDAO().getMaSuatChieu(suatChieu), java.sql.Date.valueOf(String.valueOf(mSP.getCboNgay().getSelectedItem())));
                    save(ms);
                } catch (UnsupportedFlavorException | IOException ex) {
                    Logger.getLogger(editMovieScheduleCard.class.getName()).log(Level.SEVERE, null, ex);
                }
                return true;
            }
        });
        jPanel1.setVisible(false);
        lblAnh.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                jPanel1.setVisible(true);
                lblDrop.setVisible(false);
            }
        });
        jPanel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                jPanel1.setVisible(true);
                lblDrop.setVisible(false);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                hoverOut();
            }
        });
        mticket.utils.mticketUtils.setFont(jLabel1, "Kodchasan-Medium.ttf", 24f);
        mticket.utils.mticketUtils.setFont(lblDrop, "Kodchasan-Medium.ttf", 24f);
        jLabel1.setText(suatChieu);
    }

    void hoverOut() {
        jPanel1.setVisible(false);
        if (!jPanel1.isVisible()) {
            jPanel1.setVisible(false);

        }
        lblDrop.setVisible(true);
    }

    void save(MovieSchedule ms) {
        if (mS == null) {
            mSDAO.insert(ms);
            mticketUtils.alert("Thêm thành công!");
            this.mS = ms;
            lblDrop.setVisible(false);
        } else if (!ms.getMaPhim().equals(mS.getMaPhim())) {
            mS.setMaPhim(getName());
            mSDAO.update(mS);
            mticketUtils.alert("Cập nhât thành công!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnXoa2 = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        lblDrop = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(270, 345));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new Color(0,0,0,150));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(270, 345));

        btnXoa2.setText("Xóa");
        btnXoa2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa2.setkEndColor(new Color(159,153,255));
        btnXoa2.setkHoverEndColor(new Color(76,76,153));
        btnXoa2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnXoa2.setkHoverStartColor(new Color(159,153,255));
        btnXoa2.setkStartColor(new Color(76,76,153));
        btnXoa2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnXoa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoa2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoa2MouseExited(evt);
            }
        });
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2kButton3ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnXoa2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnXoa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 340));
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        lblAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new Color(159, 153, 255)));
        lblAnh.setPreferredSize(new java.awt.Dimension(270, 345));
        lblAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAnhMouseExited(evt);
            }
        });
        add(lblAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 340));

        lblDrop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDrop.setText("Drop here !");
        lblDrop.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new Color(159, 153, 255)));
        lblDrop.setPreferredSize(new java.awt.Dimension(270, 345));
        lblDrop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDropMouseExited(evt);
            }
        });
        add(lblDrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void lblAnhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhMouseExited
        // TODO add your handling code here:
        hoverOut();
    }//GEN-LAST:event_lblAnhMouseExited

    private void btnXoa2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoa2MouseEntered
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        lblDrop.setVisible(false);
    }//GEN-LAST:event_btnXoa2MouseEntered

    private void btnXoa2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoa2MouseExited
        // TODO add your handling code here:
        hoverOut();
    }//GEN-LAST:event_btnXoa2MouseExited

    private void btnXoa2kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2kButton3ActionPerformed
        // TODO add your handling code here:
        if (mS != null) {
            mSDAO.delete(mS);
            mticketUtils.alert("Xóa thành công !");
            lblDrop.setVisible(true);
            mSP.selectMovieSchedule();
        }
    }//GEN-LAST:event_btnXoa2kButton3ActionPerformed

    private void lblDropMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDropMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDropMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnXoa2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblDrop;
    // End of variables declaration//GEN-END:variables
}
