/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mticket.component.food;

import mticket.component.movie.listMovie;
import java.awt.Color;
import java.awt.Cursor;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import mticket.entity.Food;
import mticket.entity.TicketDetail;
import mticket.utils.mticketUtils;

/**
 *
 * @author HuyTinh
 */
public class foodCard extends javax.swing.JPanel {

    /**
     * Creates new form foodCard
     */
    private JLabel lblThanhTien;

    public static double foodPrice;

    public foodCard() {
        initComponents();
        mticketUtils.setFont(lblNumber, "Kodchasan-Medium.ttf", 22f);
        mticketUtils.setFont(txtCombo, "Kodchasan-Bold.ttf", 21f);
        mticketUtils.setFont(txtGia, "Kodchasan-Medium.ttf", 18f);
        mticketUtils.setFont(txtMoTa, "Kodchasan-Medium.ttf", 18f);
    }

    public void initData(Food f, JLabel jl) {
        txtCombo.setText(f.getTenThucAn());
        txtGia.setText("Giá: " + NumberFormat.getCurrencyInstance(new Locale("vn", "vn")).format(f.getGiaThucAn()));
        txtGia.setToolTipText(String.valueOf(f.getGiaThucAn()));
        txtMoTa.setText(f.getMoTaThucAn());
        mticketUtils.setIcon(new ImageIcon(getClass().getResource("/mticket/image/" + f.getHinhThucAn())), lblAnh);
        lblThanhTien = jl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel3 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel4 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel5 = new com.k33ptoo.components.KGradientPanel();
        txtCombo = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnDecre = new com.k33ptoo.components.KButton();
        btnIncre = new com.k33ptoo.components.KButton();
        lblNumber = new javax.swing.JLabel();
        txtGia = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(725, 270));
        setRequestFocusEnabled(false);

        kGradientPanel2.setkEndColor(new Color(159, 153, 255));
        kGradientPanel2.setkStartColor(new Color(159, 153, 255));
        kGradientPanel2.setOpaque(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setOpaque(false);

        kGradientPanel3.setFocusable(false);
        kGradientPanel3.setkBorderRadius(8);
        kGradientPanel3.setkEndColor(new Color(76,76,153));
        kGradientPanel3.setkStartColor(new Color(76,76,153));
        kGradientPanel3.setOpaque(false);

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        kGradientPanel4.setFocusable(false);
        kGradientPanel4.setkEndColor(new Color(76,76,153));
        kGradientPanel4.setkStartColor(new Color(76,76,153));
        kGradientPanel4.setOpaque(false);

        kGradientPanel5.setFocusable(false);
        kGradientPanel5.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel5.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel5.setOpaque(false);

        txtCombo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCombo.setForeground(new Color(76,76,153));
        txtCombo.setText("Tên combo:");
        txtCombo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(159,153,255)));

        jScrollPane4.setBackground(new Color(0,0,0,0));
        jScrollPane4.setBorder(null);
        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setFocusable(false);
        jScrollPane4.setOpaque(false);

        txtMoTa.setEditable(false);
        txtMoTa.setBackground(new java.awt.Color(255, 255, 255));
        txtMoTa.setColumns(20);
        txtMoTa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMoTa.setLineWrap(true);
        txtMoTa.setRows(4);
        txtMoTa.setText("a\n");
        txtMoTa.setWrapStyleWord(true);
        txtMoTa.setBorder(null);
        txtMoTa.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtMoTa.setFocusable(false);
        txtMoTa.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtMoTa.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(txtMoTa);

        btnDecre.setText("-");
        btnDecre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDecre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDecre.setkEndColor(new Color(159,153,255));
        btnDecre.setkHoverEndColor(new Color(76,76,153));
        btnDecre.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDecre.setkHoverStartColor(new Color(159,153,255));
        btnDecre.setkStartColor(new Color(76,76,153));
        btnDecre.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnDecre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecrekButton3ActionPerformed(evt);
            }
        });

        btnIncre.setText("+");
        btnIncre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIncre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIncre.setkEndColor(new Color(159,153,255));
        btnIncre.setkHoverEndColor(new Color(76,76,153));
        btnIncre.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnIncre.setkHoverStartColor(new Color(159,153,255));
        btnIncre.setkStartColor(new Color(76,76,153));
        btnIncre.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnIncre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncrekButton3ActionPerformed(evt);
            }
        });

        lblNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumber.setText("0");

        txtGia.setText("jLabel1");

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                        .addComponent(btnDecre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIncre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(txtGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCombo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGia)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDecre, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnIncre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new Color(76,76,153)));
        lblAnh.setPreferredSize(new java.awt.Dimension(206, 241));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDecrekButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecrekButton3ActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(lblNumber.getText()) > 0) {
            lblNumber.setText(String.valueOf(Integer.parseInt(lblNumber.getText()) - 1));
            foodPrice -= Double.parseDouble(txtGia.getToolTipText());
            lblThanhTien.setText("Tạm tính: " + mticketUtils.toCurrency(mticketUtils.toDouble(lblThanhTien.getText()) - Double.parseDouble(txtGia.getToolTipText())));
            listMovie.tk.getThucAnDat().get(getName()).setSoLuong(Integer.parseInt(lblNumber.getText()));
        }
        if (Integer.parseInt(lblNumber.getText()) - 1 < 0) {
            listMovie.tk.getThucAnDat().remove(getName());
        }
    }//GEN-LAST:event_btnDecrekButton3ActionPerformed

    private void btnIncrekButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncrekButton3ActionPerformed
        // TODO add your handling code here:
        lblNumber.setText(String.valueOf(Integer.parseInt(lblNumber.getText()) + 1));
        foodPrice += Double.parseDouble(txtGia.getToolTipText());
        lblThanhTien.setText("Tạm tính: " + mticketUtils.toCurrency(mticketUtils.toDouble(lblThanhTien.getText()) + Double.parseDouble(txtGia.getToolTipText())));
        TicketDetail tD = new TicketDetail();
        tD.setThucAn(getName());
        tD.setGiaThucAn(Double.parseDouble(getToolTipText()));
        tD.setSoLuong(Integer.parseInt(lblNumber.getText()));
        listMovie.tk.getThucAnDat().put(getName(), tD);
    }//GEN-LAST:event_btnIncrekButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnDecre;
    private com.k33ptoo.components.KButton btnIncre;
    private javax.swing.JScrollPane jScrollPane4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel5;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel txtCombo;
    private javax.swing.JLabel txtGia;
    private javax.swing.JTextArea txtMoTa;
    // End of variables declaration//GEN-END:variables
}
