/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mticket.component.food;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JLabel;
import mticket.entity.Food;

/**
 *
 * @author HuyTinh
 */
public class listFood extends javax.swing.JPanel {

    /**
     * Creates new form foodList
     */
    public listFood() {
        initComponents();
    }

    public void initFood(List<Food> listFood, JLabel jl) {
        removeAll();
        setPreferredSize(new Dimension(getParent().getPreferredSize().width, 10));
        for (Food food : listFood) {
            int i = listFood.indexOf(food);
            foodCard fC = new foodCard();
            fC.setName(food.getMaThucAn());
            fC.setToolTipText(String.valueOf(food.getGiaThucAn()));
            fC.initData(food, jl);
            this.add(fC);
            if (i % 2 == 0) {
                this.setPreferredSize(new Dimension(getParent().getPreferredSize().width, getPreferredSize().height + fC.getPreferredSize().height + 15));
            }
        }
        this.repaint();
        this.validate();
    }

//    public void refresh
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(960, 30));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 12, 15));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
