/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mticket.component.seat;

import mticket.component.movie.showTimeMovie;
import java.awt.Color;
import java.awt.Dimension;
import java.time.LocalDate;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import mticket.dao.movieScheduleDAO;

/**
 *
 * @author HuyTinh
 */
public class seatBooking extends javax.swing.JPanel {

    /**
     * Creates new form seatBooking
     */
    public seatBooking() {
        initComponents();
 }
    
    public void initShowTime(JLabel jl, String maPhim){
        suatJPanel.removeAll();
        List<Object[]> listShowTime = movieScheduleDAO.getShowTimeByIdMovieAndDate(maPhim, LocalDate.now().toString());
        ButtonGroup bG = new ButtonGroup();
        for (int i = 0; i < listShowTime.size(); i++) {
            showTimeMovie sT = new showTimeMovie(phongJPanel, initSeatPanel, jl,maPhim, new Color(159, 153, 255), new Color(76, 76, 153));
            sT.setText(String.valueOf(listShowTime.get(i)[1]));
            sT.setName(String.valueOf(listShowTime.get(i)[0]));
            sT.setPreferredSize(new Dimension(sT.getPreferredSize().width + 155, sT.getPreferredSize().height + 40));
            bG.add(sT);
            if (i == 0) {
                sT.setSelected(true);
            }
            suatJPanel.add(sT);
        }
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movie6 = new com.k33ptoo.components.KGradientPanel();
        movieSeatPanel = new com.k33ptoo.components.KGradientPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        initSeatPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        suatJPanel = new javax.swing.JPanel();
        phongJPanel = new javax.swing.JPanel();

        setOpaque(false);

        movie6.setBackground(new java.awt.Color(255, 255, 255));
        movie6.setkBorderRadius(18);
        movie6.setkEndColor(new Color(76,76,153));
        movie6.setkStartColor(new Color(159,153,255));
        movie6.setOpaque(false);

        movieSeatPanel.setBackground(new java.awt.Color(255, 255, 255));
        movieSeatPanel.setkBorderRadius(18);
        movieSeatPanel.setkEndColor(new java.awt.Color(255, 255, 255));
        movieSeatPanel.setkStartColor(new java.awt.Color(255, 255, 255));
        movieSeatPanel.setOpaque(false);

        jPanel3.setBackground(new Color(159,153,255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ghế đơn");

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ghế đôi");

        jPanel5.setBackground(new Color(76, 76, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ghế đã chọn");

        initSeatPanel.setBackground(new java.awt.Color(255, 255, 255));
        initSeatPanel.setPreferredSize(new java.awt.Dimension(20, 800));
        initSeatPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 15));

        javax.swing.GroupLayout movieSeatPanelLayout = new javax.swing.GroupLayout(movieSeatPanel);
        movieSeatPanel.setLayout(movieSeatPanelLayout);
        movieSeatPanelLayout.setHorizontalGroup(
            movieSeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movieSeatPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(movieSeatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(initSeatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        movieSeatPanelLayout.setVerticalGroup(
            movieSeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movieSeatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(initSeatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(movieSeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movieSeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(movieSeatPanelLayout.createSequentialGroup()
                            .addGroup(movieSeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(movieSeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(movieSeatPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(16, 16, 16)))
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movieSeatPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(22, 22, 22)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movieSeatPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27))))
        );

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Suất chiếu:");
        mticket.utils.mticketUtils.setFont(jLabel5,"Kodchasan-Medium.ttf", 32f);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phòng:");
        mticket.utils.mticketUtils.setFont(jLabel6, "Kodchasan-Medium.ttf", 32f);

        suatJPanel.setOpaque(false);
        suatJPanel.setPreferredSize(new java.awt.Dimension(200, 178));
        suatJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        phongJPanel.setOpaque(false);
        phongJPanel.setPreferredSize(new java.awt.Dimension(200, 178));
        phongJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        javax.swing.GroupLayout movie6Layout = new javax.swing.GroupLayout(movie6);
        movie6.setLayout(movie6Layout);
        movie6Layout.setHorizontalGroup(
            movie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movie6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addGroup(movie6Layout.createSequentialGroup()
                        .addGroup(movie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(phongJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suatJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(movieSeatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        movie6Layout.setVerticalGroup(
            movie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movie6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suatJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phongJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                    .addComponent(movieSeatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(movie6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(movie6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel initSeatPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private com.k33ptoo.components.KGradientPanel movie6;
    private com.k33ptoo.components.KGradientPanel movieSeatPanel;
    private javax.swing.JPanel phongJPanel;
    private javax.swing.JPanel suatJPanel;
    // End of variables declaration//GEN-END:variables
}
