/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mticket.component.movie;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.TransferHandler;
import mticket.component.searchBar.SearchOption;
import mticket.component.sweetAlert.SweetAlert;
import mticket.dao.movieDAO;
import mticket.entity.Movie;
import mticket.utils.importHelper;
import mticket.utils.mticketUtils;
import mticket.view.editMovieJDialog;
import mticket.view.editStaffJDialog;
import mticket.view.managerJFrame;

/**
 *
 * @author HuyTinh
 */
public class listEditMovieCard extends javax.swing.JPanel {

    /**
     * Creates new form listEditMovieCard
     */
    private movieDAO mDAO = new movieDAO();
    private List<Movie> lMovie = mDAO.selectAll();
    public static List<Integer> ldMovie = new ArrayList<>();
    public static listEditMovieCard lM;

    public listEditMovieCard() {
        initComponents();
        this.lM = this;
        jTextFieldSearchOption1.addOption(new SearchOption("ID", new ImageIcon(getClass().getResource("/mticket/image/id.png"))));
        jTextFieldSearchOption1.addOption(new SearchOption("Name", new ImageIcon(getClass().getResource("/mticket/image/user.png"))));
        setTransferHandler(new TransferHandler() {
            @Override
            public boolean canImport(TransferHandler.TransferSupport support) {
                return true;
            }

            @Override
            public boolean importData(JComponent comp, Transferable t) {
                try {
                    List<File> files = (List<File>) t.getTransferData(DataFlavor.javaFileListFlavor);
                    for (File file : files) {
                        if (file.isFile()) {
                            if (importHelper.importFileExcel(movieDAO.insert_sql, file)) {
                                initData(new movieDAO().selectAll());
                            }
                        } else {
                            for (File listFile : file.listFiles()) {
                                mticketUtils.save(listFile);
                            }
                        }
                    }
                } catch (UnsupportedFlavorException ex) {
                    Logger.getLogger(editStaffJDialog.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(editStaffJDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                return true;
            }
        });
    }

    public void initData(List<Movie> lMovie) {
        jPanel1.setPreferredSize(new Dimension(getParent().getPreferredSize().width, 10));
        jPanel1.removeAll();
        for (int i = 0; i < lMovie.size(); i++) {
            editMovieCard eMC = new editMovieCard(lMovie.get(i));
            eMC.setName(String.valueOf(i));
            jPanel1.add(eMC);
            if (i % 7 == 0) {
                jPanel1.setPreferredSize(new Dimension(getParent().getPreferredSize().width, jPanel1.getPreferredSize().height + eMC.getPreferredSize().height + 5));
            }
        }
        repaint();
        revalidate();
    }

    void search(String str) {
        if (str.equals("ID")) {
            initData(new movieDAO().selectBySql("select * from Phim where maPhim like ?", "%" + jTextFieldSearchOption1.getText() + "%"));
        } else if (str.equals("Name")) {
            initData(new movieDAO().selectBySql("select * from Phim where tenPhim like ?", "%" + jTextFieldSearchOption1.getText() + "%"));
        }
    }

    void deleteMuti() {
        if (ldMovie.size() == 2) {
            int min = Collections.min(ldMovie);
            int max = Collections.max(ldMovie);
            for (int i = min; i <= max; i++) {
                mDAO.delete(lMovie.get(i));
            }
        } else {
            for (Integer i : ldMovie) {
                mDAO.delete(lMovie.get(i));
            }
        }
        initData(mDAO.selectAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldSearchOption1 = new mticket.component.searchBar.JTextFieldSearchOption();
        btnAdd = new com.k33ptoo.components.KButton();

        setPreferredSize(new java.awt.Dimension(1090, 479));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(0, 1));

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 10));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(jPanel1);

        jTextFieldSearchOption1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchOption1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchOption1KeyTyped(evt);
            }
        });

        btnAdd.setText("ADD");
        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setkEndColor(new Color(159,153,255));
        btnAdd.setkHoverEndColor(new Color(76,76,153));
        mticketUtils.setFont(btnAdd, "Kodchasan-Medium.ttf", 18f);
        btnAdd.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAdd.setkHoverStartColor(new Color(159,153,255));
        btnAdd.setkStartColor(new Color(76,76,153));
        btnAdd.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddkButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSearchOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldSearchOption1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchOption1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchOption1KeyReleased
        search(jTextFieldSearchOption1.getSelectedOption().getName());
    }//GEN-LAST:event_jTextFieldSearchOption1KeyReleased

    private void btnAddkButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddkButton3ActionPerformed
        // TODO add your handling code here:
        SweetAlert sA = new editMovieJDialog(managerJFrame.mFrame, true);
        sA.showAlert();
    }//GEN-LAST:event_btnAddkButton3ActionPerformed

    private void jTextFieldSearchOption1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchOption1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchOption1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAdd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private mticket.component.searchBar.JTextFieldSearchOption jTextFieldSearchOption1;
    // End of variables declaration//GEN-END:variables
}
