/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mticket.component.report;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.text.DateFormatSymbols;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import mticket.component.transitionForm.Transition;
import mticket.dao.movieDAO;
import mticket.dao.reportDAO;
import mticket.entity.Movie;
import mticket.utils.mticketUtils;

/**
 *
 * @author HuyTinh
 */
public class detailReportMovie extends Transition {

    /**
     * Creates new form detailMovie
     */
    movieDAO mDAO = new movieDAO();
    Map<String, Movie> mMovie = new HashMap<>();

    public detailReportMovie() {
        initComponents();
        chart.setFillColor(true);
        chart.addLegend("Movie", Color.decode("#9f99ff"), Color.decode("#4c4c99"));
        mticket.utils.mticketUtils.setFont(cboMovie, "Kodchasan-Medium.ttf", 14f);
        mticket.utils.mticketUtils.setFont(btnBack, "Kodchasan-Medium.ttf", 14f);
        mticket.utils.mticketUtils.setFont(chart, "Kodchasan-Bold.ttf", 12f);
        chart.setdRM(this);
        chart.setfTST(formTransition1);
        chart.getBlankPlotChart().setCursor(new Cursor(Cursor.HAND_CURSOR));
        new Thread(new Runnable() {
            @Override
            public void run() {
                initDataMovie();
                initDataForComboBox();
            }
        }).start();

    }

    void initDataMovie() {
        for (Movie mv : mDAO.selectAll()) {
            mMovie.put(mv.getTenPhim(), mv);
        }
    }

    void initDataForComboBox() {
        DefaultComboBoxModel cboModel = (DefaultComboBoxModel) cboMovie.getModel();
        cboModel.removeAllElements();
        for (String string : mMovie.keySet()) {
            cboModel.addElement(string);
        }
    }

    public void initDetailMovie(Movie mv) {
        if (mv.getTenPhim().length() > 38) {
            txtTenPhim.setText(mv.getTenPhim().substring(0, 39) + "...");
        } else {
            txtTenPhim.setText(mv.getTenPhim());
        }
        mticket.utils.mticketUtils.setFont(txtTenPhim, "Kodchasan-Medium.ttf", 36f);
        mticketUtils.setIcon(new ImageIcon(getClass().getResource("/mticket/image/" + mv.getHinhAnh())), pictureBox1, 20);
        setName(mv.getMaPhim());
        setData(mv.getMaPhim());
    }

    public void setData(String idMovie) {
        for (int i = 0; i < 12; i++) {
            String monthString = new DateFormatSymbols().getMonths()[i];
            List<Object[]> lO = reportDAO.getAmountMovieByIdAdMonth(idMovie, monthString);
            double n = (lO.isEmpty()) ? 0 : Double.parseDouble(String.valueOf(lO.get(0)[0]));
            chart.addData(new ModelChart(monthString, new double[]{n}));
        }
        chart.start();
    }

    public void eventBack(MouseAdapter event) {
        btnBack.addMouseListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movie5 = new com.k33ptoo.components.KGradientPanel();
        pictureBox1 = new mticket.component.pictureBox.PictureBox();
        txtTenPhim = new javax.swing.JLabel();
        chart = new mticket.component.report.CurveLineChart();
        btnBack = new com.k33ptoo.components.KButton();
        movie15 = new com.k33ptoo.components.KGradientPanel();
        formTransition1 = new mticket.component.transitionForm.FormTransition();
        cboMovie = new mticket.component.comboSuggestion.ComboBoxSuggestionMovie();

        setBackground(new java.awt.Color(255, 255, 255));

        movie5.setBackground(new java.awt.Color(255, 255, 255));
        movie5.setkBorderRadius(18);
        movie5.setkEndColor(new Color(76,76,153));
        movie5.setkStartColor(new Color(159,153,255));
        movie5.setOpaque(false);
        movie5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        movie5.add(pictureBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 572, 732));

        txtTenPhim.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        txtTenPhim.setText("Tên phim:");
        txtTenPhim.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new Color(159,153,255)));

        chart.setForeground(new java.awt.Color(0, 0, 0));

        btnBack.setText("< Back");
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.setkEndColor(new Color(159,153,255));
        btnBack.setkHoverEndColor(new Color(76,76,153));
        btnBack.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnBack.setkHoverStartColor(new Color(159,153,255));
        btnBack.setkStartColor(new Color(76,76,153));
        btnBack.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackkButton3ActionPerformed(evt);
            }
        });

        movie15.setBackground(new java.awt.Color(255, 255, 255));
        movie15.setkBorderRadius(18);
        movie15.setkEndColor(new Color(76,76,153));
        movie15.setkStartColor(new Color(159,153,255));
        movie15.setOpaque(false);

        javax.swing.GroupLayout movie15Layout = new javax.swing.GroupLayout(movie15);
        movie15.setLayout(movie15Layout);
        movie15Layout.setHorizontalGroup(
            movie15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
            .addGroup(movie15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(movie15Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(formTransition1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );
        movie15Layout.setVerticalGroup(
            movie15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
            .addGroup(movie15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(movie15Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(formTransition1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(9, Short.MAX_VALUE)))
        );

        cboMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMovieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(movie5, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenPhim, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
                            .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(599, Short.MAX_VALUE)
                    .addComponent(movie15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(cboMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movie5, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTenPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chart, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(494, Short.MAX_VALUE)
                    .addComponent(movie15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackkButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackkButton3ActionPerformed
        // TODO add your handling code here:
        chart.clear();
        formTransition1.showForm(chart.dDRM);
    }//GEN-LAST:event_btnBackkButton3ActionPerformed

    private void cboMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMovieActionPerformed
        // TODO add your handling code here:
        chart.clear();
        Movie mv = mMovie.get(String.valueOf(cboMovie.getSelectedItem()));
        if (mv != null) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    initDetailMovie(mv);
                }
            }).start();
            formTransition1.setName(mv.getMaPhim());
            formTransition1.showForm(chart.dDRM);
            chart.dDRM.initDataDateInMonth(1, formTransition1.getName());
        }
    }//GEN-LAST:event_cboMovieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnBack;
    private mticket.component.comboSuggestion.ComboBoxSuggestionMovie cboMovie;
    private mticket.component.report.CurveLineChart chart;
    private mticket.component.transitionForm.FormTransition formTransition1;
    private com.k33ptoo.components.KGradientPanel movie15;
    private com.k33ptoo.components.KGradientPanel movie5;
    private mticket.component.pictureBox.PictureBox pictureBox1;
    private javax.swing.JLabel txtTenPhim;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component[] initTransition() {
        return new Component[]{};
    }
}
