/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mticket.component.report;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.border.TitledBorder;
import mticket.component.transitionForm.Transition;
import mticket.dao.movieDAO;
import mticket.entity.Movie;
import mticket.utils.mticketUtils;

/**
 *
 * @author HuyTinh
 */
public class movieReportJPanel extends Transition {

    /**
     * Creates new form movieReportJPanel
     */
    public movieReportJPanel() {
        try {
            initComponents();
            mticket.utils.mticketUtils.setFont(jLabel1, "Kodchasan-Medium.ttf", 28f);
            mticket.utils.mticketUtils.setFont(jLabel2, "Kodchasan-Medium.ttf", 32f);
            mticket.utils.mticketUtils.setFont(jLabel3, "Kodchasan-Medium.ttf", 18f);
            mticket.utils.mticketUtils.setFont(jLabel4, "Kodchasan-Medium.ttf", 13f);
            mticket.utils.mticketUtils.setFont(jLabel5, "Kodchasan-Medium.ttf", 13f);
            mticket.utils.mticketUtils.setFont(jLabel6, "Kodchasan-Medium.ttf", 13f);
            mticket.utils.mticketUtils.setFont(jLabel7, "Kodchasan-Medium.ttf", 13f);
            mticket.utils.mticketUtils.setFont(txtMoTa, "Kodchasan-Medium.ttf", 16f);

            mticket.utils.mticketUtils.setFont(jLabel8, "Kodchasan-Medium.ttf", 20f);
            mticket.utils.mticketUtils.setFont(jLabel9, "Kodchasan-Medium.ttf", 18f);
            mticket.utils.mticketUtils.setFont(jLabel12, "Kodchasan-Medium.ttf", 14f);
            mticket.utils.mticketUtils.setFont(jLabel13, "Kodchasan-Medium.ttf", 12f);
            ((TitledBorder) jScrollPane4.getViewportBorder()).setTitleFont(Font.createFont(Font.TRUETYPE_FONT, new File(reportPanel.class.getResource("/mticket/font/Kodchasan-Medium.ttf").toURI())).deriveFont(12f));
        } catch (URISyntaxException ex) {
            Logger.getLogger(movieReportJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FontFormatException ex) {
            Logger.getLogger(movieReportJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(movieReportJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        pictureBox2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        pictureBox3.setCursor(new Cursor(Cursor.HAND_CURSOR));
        pictureBox6.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    public void initData(List<Object[]> objs) {
        Movie mV_1 = new movieDAO().selectById(String.valueOf(objs.get(0)[0]));

        jLabel2.setText(mV_1.getTenPhim());
        jLabel4.setText("Đạo Diễn: " + mV_1.getDaoDien());
        jLabel5.setText("Diễn Viên: " + mV_1.getDienVien());
        jLabel6.setText("Ngày Công Chiếu: " + mV_1.getNgayChieu().toLocalDate().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")));
        jLabel7.setText("Thời Lượng: " + mV_1.getThoiLuong());
        txtMoTa.setText(mV_1.getMoTa());
        jLabel3.setText("Doang Thu:  " + mticketUtils.toCurrency(Double.parseDouble(String.valueOf(objs.get(0)[1]))) + " (" + objs.get(0)[2] + "%)"); //mticketUtils.toCurrency(mC.getValues()[0])
        mticketUtils.setIcon(new ImageIcon(getClass().getResource("/mticket/image/" + mV_1.getHinhAnh())), pictureBox2, 16);

        jLabel9.setText("Doanh Thu");
        mticketUtils.setIcon(new ImageIcon(), pictureBox3, 16);

        jLabel13.setText("Doanh Thu");
        mticketUtils.setIcon(new ImageIcon(), pictureBox6, 16);

        if (objs.size() > 1) {
            Movie mV_2 = new movieDAO().selectById(String.valueOf(objs.get(1)[0]));
            jLabel9.setText(mticketUtils.toCurrency(Double.parseDouble(String.valueOf(objs.get(1)[1]))) + " (" + objs.get(1)[2] + "%)");
            mticketUtils.setIcon(new ImageIcon(getClass().getResource("/mticket/image/" + mV_2.getHinhAnh())), pictureBox3, 16);
            if (objs.size() == 3) {
                Movie mV_3 = new movieDAO().selectById(String.valueOf(objs.get(2)[0]));
                jLabel13.setText(mticketUtils.toCurrency(Double.parseDouble(String.valueOf(objs.get(2)[1]))) + " (" + objs.get(2)[2] + "%)");
                mticketUtils.setIcon(new ImageIcon(getClass().getResource("/mticket/image/" + mV_3.getHinhAnh())), pictureBox6, 16);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movie10 = new com.k33ptoo.components.KGradientPanel();
        movie12 = new com.k33ptoo.components.KGradientPanel();
        pictureBox2 = new mticket.component.pictureBox.PictureBox();
        movie13 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        movie14 = new com.k33ptoo.components.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        movie15 = new com.k33ptoo.components.KGradientPanel();
        pictureBox3 = new mticket.component.pictureBox.PictureBox();
        movie17 = new com.k33ptoo.components.KGradientPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        movie18 = new com.k33ptoo.components.KGradientPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        movie20 = new com.k33ptoo.components.KGradientPanel();
        pictureBox6 = new mticket.component.pictureBox.PictureBox();

        movie10.setBackground(new java.awt.Color(255, 255, 255));
        movie10.setkBorderRadius(18);
        movie10.setkEndColor(new Color(76,76,153));
        movie10.setkFillBackground(false);
        movie10.setkStartColor(new Color(159,153,255));
        movie10.setOpaque(false);

        movie12.setBackground(new java.awt.Color(255, 255, 255));
        movie12.setkBorderRadius(18);
        movie12.setkEndColor(new Color(76,76,153));
        movie12.setkStartColor(new Color(159,153,255));
        movie12.setOpaque(false);

        javax.swing.GroupLayout movie12Layout = new javax.swing.GroupLayout(movie12);
        movie12.setLayout(movie12Layout);
        movie12Layout.setHorizontalGroup(
            movie12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        movie12Layout.setVerticalGroup(
            movie12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        movie13.setBackground(new java.awt.Color(255, 255, 255));
        movie13.setkBorderRadius(18);
        movie13.setkEndColor(new Color(159,153,255));
        movie13.setkStartColor(new Color(159,153,255));
        movie13.setOpaque(false);

        jLabel1.setForeground(new Color(249,212,35));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("#1");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout movie13Layout = new javax.swing.GroupLayout(movie13);
        movie13.setLayout(movie13Layout);
        movie13Layout.setHorizontalGroup(
            movie13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        movie13Layout.setVerticalGroup(
            movie13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movie13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        movie14.setBackground(new java.awt.Color(255, 255, 255));
        movie14.setkBorderRadius(18);
        movie14.setkEndColor(new java.awt.Color(204, 204, 255));
        movie14.setkStartColor(new Color(159,153,255));
        movie14.setOpaque(false);
        movie14.setPreferredSize(new java.awt.Dimension(700, 200));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doanh Thu:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Đạo Diễn:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Diễn Viên:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày Công chiếu:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Thời Lượng:");

        jScrollPane4.setBackground(new Color(0,0,0,0));
        jScrollPane4.setBorder(null);
        jScrollPane4.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mô tả:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setOpaque(false);
        jScrollPane4.getVerticalScrollBar().setPreferredSize(new Dimension(0, 1));

        txtMoTa.setColumns(20);
        txtMoTa.setLineWrap(true);
        txtMoTa.setRows(4);
        txtMoTa.setWrapStyleWord(true);
        txtMoTa.setBorder(null);
        txtMoTa.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtMoTa.setFocusable(false);
        txtMoTa.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtMoTa.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(txtMoTa);

        javax.swing.GroupLayout movie14Layout = new javax.swing.GroupLayout(movie14);
        movie14.setLayout(movie14Layout);
        movie14Layout.setHorizontalGroup(
            movie14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movie14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movie14Layout.createSequentialGroup()
                        .addGroup(movie14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(movie14Layout.createSequentialGroup()
                                .addGroup(movie14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movie14Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(movie14Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(266, 266, 266))))
        );
        movie14Layout.setVerticalGroup(
            movie14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movie14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(movie14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        movie15.setBackground(new java.awt.Color(255, 255, 255));
        movie15.setkBorderRadius(18);
        movie15.setkEndColor(new Color(76,76,153));
        movie15.setkStartColor(new Color(159,153,255));
        movie15.setOpaque(false);

        javax.swing.GroupLayout movie15Layout = new javax.swing.GroupLayout(movie15);
        movie15.setLayout(movie15Layout);
        movie15Layout.setHorizontalGroup(
            movie15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );
        movie15Layout.setVerticalGroup(
            movie15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox3, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        movie17.setBackground(new java.awt.Color(255, 255, 255));
        movie17.setkBorderRadius(18);
        movie17.setkEndColor(new Color(159,153,255));
        movie17.setkStartColor(new Color(159,153,255));
        movie17.setOpaque(false);

        jLabel8.setForeground(new Color(249,212,35));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("#2");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Doanh Thu");

        javax.swing.GroupLayout movie17Layout = new javax.swing.GroupLayout(movie17);
        movie17.setLayout(movie17Layout);
        movie17Layout.setHorizontalGroup(
            movie17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        movie17Layout.setVerticalGroup(
            movie17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movie17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        movie18.setBackground(new java.awt.Color(255, 255, 255));
        movie18.setkBorderRadius(18);
        movie18.setkEndColor(new Color(159,153,255));
        movie18.setkStartColor(new Color(159,153,255));
        movie18.setOpaque(false);

        jLabel12.setForeground(new Color(249,212,35));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("#3");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Doanh Thu");

        javax.swing.GroupLayout movie18Layout = new javax.swing.GroupLayout(movie18);
        movie18.setLayout(movie18Layout);
        movie18Layout.setHorizontalGroup(
            movie18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        movie18Layout.setVerticalGroup(
            movie18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movie18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        movie20.setBackground(new java.awt.Color(255, 255, 255));
        movie20.setkBorderRadius(18);
        movie20.setkEndColor(new Color(76,76,153));
        movie20.setkStartColor(new Color(159,153,255));
        movie20.setOpaque(false);

        javax.swing.GroupLayout movie20Layout = new javax.swing.GroupLayout(movie20);
        movie20.setLayout(movie20Layout);
        movie20Layout.setHorizontalGroup(
            movie20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox6, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );
        movie20Layout.setVerticalGroup(
            movie20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox6, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout movie10Layout = new javax.swing.GroupLayout(movie10);
        movie10.setLayout(movie10Layout);
        movie10Layout.setHorizontalGroup(
            movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movie12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(movie14, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addComponent(movie13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movie15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movie18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(movie10Layout.createSequentialGroup()
                        .addComponent(movie20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movie10Layout.createSequentialGroup()
                    .addContainerGap(1120, Short.MAX_VALUE)
                    .addComponent(movie17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        movie10Layout.setVerticalGroup(
            movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movie10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(movie12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(movie10Layout.createSequentialGroup()
                            .addComponent(movie13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(movie14, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))
                    .addGroup(movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(movie15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, movie10Layout.createSequentialGroup()
                            .addComponent(movie18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(movie20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
            .addGroup(movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(movie10Layout.createSequentialGroup()
                    .addGap(245, 245, 245)
                    .addComponent(movie17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(movie10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(movie10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private com.k33ptoo.components.KGradientPanel movie10;
    private com.k33ptoo.components.KGradientPanel movie12;
    private com.k33ptoo.components.KGradientPanel movie13;
    private com.k33ptoo.components.KGradientPanel movie14;
    private com.k33ptoo.components.KGradientPanel movie15;
    private com.k33ptoo.components.KGradientPanel movie17;
    private com.k33ptoo.components.KGradientPanel movie18;
    private com.k33ptoo.components.KGradientPanel movie20;
    private mticket.component.pictureBox.PictureBox pictureBox2;
    private mticket.component.pictureBox.PictureBox pictureBox3;
    private mticket.component.pictureBox.PictureBox pictureBox6;
    private javax.swing.JTextArea txtMoTa;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component[] initTransition() {
        return movie10.getComponents();
    }
}
