/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mticket.component.report;

import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.ImageIcon;
import mticket.component.transitionForm.Transition;
import mticket.dao.foodDAO;
import mticket.dao.movieDAO;
import mticket.entity.Food;
import mticket.entity.Movie;
import mticket.utils.mticketUtils;

/**
 *
 * @author HuyTinh
 */
public class totalReportJPanel1 extends Transition {

    /**
     * Creates new form movieReportJPanel
     */
    public totalReportJPanel1() {
        initComponents();
        mticket.utils.mticketUtils.setFont(lblMovie, "Kodchasan-Medium.ttf", 22f);
        mticket.utils.mticketUtils.setFont(lblFood, "Kodchasan-Medium.ttf", 22f);
        mticket.utils.mticketUtils.setFont(jLabel1, "Kodchasan-Medium.ttf", 24f);
        mticket.utils.mticketUtils.setFont(jLabel2, "Kodchasan-Medium.ttf", 24f);
        mticket.utils.mticketUtils.setFont(jLabel3, "Kodchasan-BoldItalic.ttf", 23f);
        mticket.utils.mticketUtils.setFont(jLabel4, "Kodchasan-BoldItalic.ttf", 23f);
        mticket.utils.mticketUtils.setFont(jLabel5, "Kodchasan-BoldItalic.ttf", 23f);
        mticket.utils.mticketUtils.setFont(jLabel6, "Kodchasan-BoldItalic.ttf", 23f);
        mticket.utils.mticketUtils.setFont(liquidProgress1, "Kodchasan-BoldItalic.ttf", 20f);
        mticket.utils.mticketUtils.setFont(liquidProgress2, "Kodchasan-BoldItalic.ttf", 20f);
        mticket.utils.mticketUtils.setFont(lblMovieMonth, "Kodchasan-SemiBoldItalic.ttf", 24f);
        mticket.utils.mticketUtils.setFont(lblFoodMonth, "Kodchasan-SemiBoldItalic.ttf", 24f);

    }

    void initData(List<Object[]> objM, List<Object[]> objF, int index) {
        Movie mV_1 = new movieDAO().selectById(String.valueOf(objM.get(0)[0]));
        Food f = new foodDAO().selectById(String.valueOf(objF.get(0)[0]));

        mticketUtils.setIcon(new ImageIcon(getClass().getResource("/mticket/image/" + mV_1.getHinhAnh())), pictureBox1, 16);
        if (mV_1.getTenPhim().length() > 31) {
            lblMovie.setText(mV_1.getTenPhim().substring(0, 32) + "...");
        } else {
            lblMovie.setText(mV_1.getTenPhim());
        }
//        double a = Double.parseDouble(String.valueOf(objM.get(0)[2]));
        liquidProgress1.setValue((int) Math.round(Double.parseDouble(String.valueOf(objM.get(0)[2]))));
        lblMovieMonth.setText("Tháng " + index);
//        lblMovie.setText(mV_1.getTenPhim());
        mticketUtils.setIcon(new ImageIcon(getClass().getResource("/mticket/image/" + f.getHinhThucAn())), pictureBox2, 16);
        if (f.getTenThucAn().length() > 31) {
            lblFood.setText(f.getTenThucAn().substring(0, 32) + "...");
        } else {
            lblFood.setText(f.getTenThucAn());
        }
        liquidProgress2.setValue((int) Math.round(Double.parseDouble(String.valueOf(objF.get(0)[2]))));
        lblFoodMonth.setText("Tháng " + index);

//        lblFood.setText(f.getTenThucAn());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movie10 = new com.k33ptoo.components.KGradientPanel();
        movie12 = new com.k33ptoo.components.KGradientPanel();
        pictureBox1 = new mticket.component.pictureBox.PictureBox();
        movie13 = new com.k33ptoo.components.KGradientPanel();
        lblMovie = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        movie14 = new com.k33ptoo.components.KGradientPanel();
        liquidProgress1 = new mticket.component.liquidProcess.LiquidProgress();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMovieMonth = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        movie15 = new com.k33ptoo.components.KGradientPanel();
        pictureBox2 = new mticket.component.pictureBox.PictureBox();
        movie16 = new com.k33ptoo.components.KGradientPanel();
        lblFood = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        movie17 = new com.k33ptoo.components.KGradientPanel();
        liquidProgress2 = new mticket.component.liquidProcess.LiquidProgress();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFoodMonth = new javax.swing.JLabel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        movie19 = new com.k33ptoo.components.KGradientPanel();
        movie21 = new com.k33ptoo.components.KGradientPanel();

        movie10.setBackground(new java.awt.Color(255, 255, 255));
        movie10.setkBorderRadius(18);
        movie10.setkEndColor(new Color(0,153,247));
        movie10.setkFillBackground(false);
        movie10.setkStartColor(new Color(241,23,18));
        movie10.setOpaque(false);

        movie12.setBackground(new java.awt.Color(255, 255, 255));
        movie12.setkBorderRadius(18);
        movie12.setkEndColor(new Color(0,153,247));
        movie12.setkStartColor(new Color(241,23,18));
        movie12.setOpaque(false);

        javax.swing.GroupLayout movie12Layout = new javax.swing.GroupLayout(movie12);
        movie12.setLayout(movie12Layout);
        movie12Layout.setHorizontalGroup(
            movie12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        movie12Layout.setVerticalGroup(
            movie12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        movie13.setBackground(new java.awt.Color(255, 255, 255));
        movie13.setkBorderRadius(18);
        movie13.setkEndColor(new Color(0,153,247));
        movie13.setkStartColor(new Color(241,23,18));
        movie13.setOpaque(false);

        lblMovie.setForeground(new java.awt.Color(204, 204, 255));

        jLabel1.setForeground(new Color(249,212,35));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("#1");

        javax.swing.GroupLayout movie13Layout = new javax.swing.GroupLayout(movie13);
        movie13.setLayout(movie13Layout);
        movie13Layout.setHorizontalGroup(
            movie13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movie13Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lblMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(movie13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(movie13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(433, Short.MAX_VALUE)))
        );
        movie13Layout.setVerticalGroup(
            movie13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMovie, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(movie13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(movie13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        movie14.setBackground(new java.awt.Color(255, 255, 255));
        movie14.setkBorderRadius(18);
        movie14.setkEndColor(new Color(0,153,247));
        movie14.setkStartColor(new Color(241,23,18));
        movie14.setOpaque(false);
        movie14.setPreferredSize(new java.awt.Dimension(700, 200));

        liquidProgress1.setAnimateColor(new java.awt.Color(204, 204, 255));
        liquidProgress1.setBorderColor(new Color(76,76,153));
        liquidProgress1.setBorderSize(2);
        liquidProgress1.setSpaceSize(2);

        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Chiếm");

        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Tổng doanh thu phim");

        lblMovieMonth.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovieMonth.setText("Tháng 2");
        lblMovieMonth.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 204, 255)));

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 204, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 255));
        kGradientPanel1.setOpaque(false);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout movie14Layout = new javax.swing.GroupLayout(movie14);
        movie14.setLayout(movie14Layout);
        movie14Layout.setHorizontalGroup(
            movie14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movie14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movie14Layout.createSequentialGroup()
                        .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(movie14Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(liquidProgress1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(movie14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(movie14Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMovieMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125))
                            .addGroup(movie14Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        movie14Layout.setVerticalGroup(
            movie14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie14Layout.createSequentialGroup()
                .addGroup(movie14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movie14Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(liquidProgress1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(movie14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(movie14Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addComponent(lblMovieMonth)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        movie15.setBackground(new java.awt.Color(255, 255, 255));
        movie15.setkBorderRadius(18);
        movie15.setkEndColor(new Color(241,23,18));
        movie15.setkStartColor(new Color(0,153,247));
        movie15.setOpaque(false);

        javax.swing.GroupLayout movie15Layout = new javax.swing.GroupLayout(movie15);
        movie15.setLayout(movie15Layout);
        movie15Layout.setHorizontalGroup(
            movie15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        movie15Layout.setVerticalGroup(
            movie15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        movie16.setBackground(new java.awt.Color(255, 255, 255));
        movie16.setkBorderRadius(18);
        movie16.setkEndColor(new Color(241,23,18));
        movie16.setkStartColor(new Color(0,153,247));
        movie16.setOpaque(false);

        lblFood.setForeground(new Color(249,212,35));

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("#1");

        javax.swing.GroupLayout movie16Layout = new javax.swing.GroupLayout(movie16);
        movie16.setLayout(movie16Layout);
        movie16Layout.setHorizontalGroup(
            movie16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movie16Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(lblFood, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(movie16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(movie16Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(434, Short.MAX_VALUE)))
        );
        movie16Layout.setVerticalGroup(
            movie16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFood, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(movie16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movie16Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        movie17.setBackground(new java.awt.Color(255, 255, 255));
        movie17.setkBorderRadius(18);
        movie17.setkEndColor(new Color(241,23,18));
        movie17.setkStartColor(new Color(0,153,247));
        movie17.setOpaque(false);
        movie17.setPreferredSize(new java.awt.Dimension(700, 200));

        liquidProgress2.setAnimateColor(new Color(249,212,35));
        liquidProgress2.setBorderColor(new Color(230,92,0));
        liquidProgress2.setBorderSize(2);
        liquidProgress2.setSpaceSize(2);

        jLabel5.setForeground(new Color(249,212,35));
        jLabel5.setText("Chiếm");

        jLabel6.setForeground(new Color(249,212,35));
        jLabel6.setText("Tổng doanh thu thức ăn");

        lblFoodMonth.setForeground(new java.awt.Color(255, 255, 255));
        lblFoodMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoodMonth.setText("Tháng 2");
        lblFoodMonth.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(249,212,35)));

        kGradientPanel2.setkEndColor(new Color(249,212,35));
        kGradientPanel2.setkStartColor(new Color(249,212,35));
        kGradientPanel2.setOpaque(false);

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout movie17Layout = new javax.swing.GroupLayout(movie17);
        movie17.setLayout(movie17Layout);
        movie17Layout.setHorizontalGroup(
            movie17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movie17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movie17Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(liquidProgress2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(movie17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(movie17Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(lblFoodMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 136, Short.MAX_VALUE))
                            .addGroup(movie17Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(kGradientPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        movie17Layout.setVerticalGroup(
            movie17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie17Layout.createSequentialGroup()
                .addGroup(movie17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movie17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(movie17Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(movie17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(liquidProgress2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(movie17Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jLabel6)
                                .addGap(0, 0, 0)
                                .addComponent(lblFoodMonth)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        movie19.setBackground(new java.awt.Color(255, 255, 255));
        movie19.setkBorderRadius(16);
        movie19.setkEndColor(new Color(241,23,18));
        movie19.setkStartColor(new Color(0,153,247));
        movie19.setOpaque(false);
        movie19.setPreferredSize(new java.awt.Dimension(32, 278));
        movie19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        movie21.setBackground(new java.awt.Color(255, 255, 255));
        movie21.setkBorderRadius(14);
        movie21.setkEndColor(new Color(0,153,247));
        movie21.setkStartColor(new Color(241,23,18));
        movie21.setOpaque(false);

        javax.swing.GroupLayout movie21Layout = new javax.swing.GroupLayout(movie21);
        movie21.setLayout(movie21Layout);
        movie21Layout.setHorizontalGroup(
            movie21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        movie21Layout.setVerticalGroup(
            movie21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        movie19.add(movie21, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 36, 270));

        javax.swing.GroupLayout movie10Layout = new javax.swing.GroupLayout(movie10);
        movie10.setLayout(movie10Layout);
        movie10Layout.setHorizontalGroup(
            movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movie10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movie12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(movie14, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(movie13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movie19, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(movie16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movie17, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movie15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        movie10Layout.setVerticalGroup(
            movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movie10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(movie15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movie19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(movie10Layout.createSequentialGroup()
                        .addComponent(movie17, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movie16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(movie10Layout.createSequentialGroup()
                        .addComponent(movie13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movie14, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                    .addComponent(movie12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movie10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movie10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblFoodMonth;
    private javax.swing.JLabel lblMovie;
    private javax.swing.JLabel lblMovieMonth;
    private mticket.component.liquidProcess.LiquidProgress liquidProgress1;
    private mticket.component.liquidProcess.LiquidProgress liquidProgress2;
    private com.k33ptoo.components.KGradientPanel movie10;
    private com.k33ptoo.components.KGradientPanel movie12;
    private com.k33ptoo.components.KGradientPanel movie13;
    private com.k33ptoo.components.KGradientPanel movie14;
    private com.k33ptoo.components.KGradientPanel movie15;
    private com.k33ptoo.components.KGradientPanel movie16;
    private com.k33ptoo.components.KGradientPanel movie17;
    private com.k33ptoo.components.KGradientPanel movie19;
    private com.k33ptoo.components.KGradientPanel movie21;
    private mticket.component.pictureBox.PictureBox pictureBox1;
    private mticket.component.pictureBox.PictureBox pictureBox2;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component[] initTransition() {
        return movie10.getComponents();
    }
}
